[package]
name = "cniic"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.7"
bytesize = "1.3.0"
csv = "1.3.0"
rayon = "1.8"
